### ISSUE TITLE
Is this even still maintained? - Quite a lot of issues/requests

### ISSUE THREAD

**Issue by Skyridr** [thiemok/discord_playtime#30]
Issues such as:

> (node:8980) UnhandledPromiseRejectionWarning: RangeError: RichEmbed field values may not be empty.
>     at RichEmbed.addField (/home/skyrider/discord/playtime/node_modules/discord.js/src/structures/RichEmbed.js:158:34)
>     at addFieldsToEmbed (/home/skyrider/discord/playtime/app/util/embedHelpers.js:122:16)
>     at /home/skyrider/discord/playtime/app/util/embedHelpers.js:149:12
>     at new Promise (<anonymous>)
>     at new F (/home/skyrider/discord/playtime/node_modules/core-js/library/modules/_export.js:36:28)
>     at generateEmbeds (/home/skyrider/discord/playtime/app/util/embedHelpers.js:135:17)
>     at /home/skyrider/discord/playtime/app/commands/gameStats.js:72:7
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> (node:8980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 70)

Commands are required to be capitalized. (Eg, !overview doesn't work while !Overview does).

You can't use userstats on a userID, a clear copy/paste of his name is required. EG:

> !UserStats @ Skyrider

Shows up:
> : I could not find <@!133631162894516225> please use an existing username

Also an ignore feature would be nice. Spotify for example isn't a game.

Kind Regards,
Skyrider

**Comment by thiemok** [comment]
Its not really, since a lot of the changes to presences, like spotify, over the last year have made tracking a bit hard. If you want to submit a or to fix some things, i'd appreciate it, but i currently dont have the time to a major rework

**Comment by valveo** [comment]
Still this is nice piece of work even you dont update it.
I am updating it to my needs (some stats about games in our gaming community). Same time I need to learn new programming language so this is good practice. 👍
